### ISSUE TITLE
addtrans (macOS 12): “Namespace Gtk not available for version 3.0"

### ISSUE THREAD

**Issue by ghost** [Rudd-O/ledgerhelpers#18]
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/addtrans", line 4, in <module>
    __import__('pkg_resources').run_script('ledgerhelpers==0.3.2', 'addtrans')
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/homebrew/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1448, in run_script
    exec(code, namespace, namespace)
  File "/opt/homebrew/lib/python3.9/site-packages/ledgerhelpers-0.3.2-py3.9.egg/EGG-INFO/scripts/addtrans", line 8, in <module>
    from ledgerhelpers.programs import addtrans
  File "/opt/homebrew/lib/python3.9/site-packages/ledgerhelpers-0.3.2-py3.9.egg/ledgerhelpers/programs/addtrans.py", line 9, in <module>
    gi.require_version("Gtk", "3.0")
  File "/opt/homebrew/lib/python3.9/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available for version %s' %
ValueError: Namespace Gtk not available for version 3.0
```

**Comment by Rudd-O** [comment]
This means you don't have Gtk 3.0 installed on your system.
