### ISSUE TITLE
Relies on missing ‘ledger’ module

### ISSUE THREAD

**Issue by ghost** [Rudd-O/ledgerhelpers#19]
```
Traceback (most recent call last):
  File "/usr/local/bin/addtrans", line 4, in <module>
    __import__('pkg_resources').run_script('ledgerhelpers==0.3.2', 'addtrans')
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/dist-packages/ledgerhelpers-0.3.2-py3.7.egg/EGG-INFO/scripts/addtrans", line 8, in <module>
    from ledgerhelpers.programs import addtrans
  File "/usr/local/lib/python3.7/dist-packages/ledgerhelpers-0.3.2-py3.7.egg/ledgerhelpers/programs/addtrans.py", line 15, in <module>
    from ledgerhelpers import gui
  File "/usr/local/lib/python3.7/dist-packages/ledgerhelpers-0.3.2-py3.7.egg/ledgerhelpers/gui.py", line 1, in <module>
    import ledger
ModuleNotFoundError: No module named 'ledger'
pi@raspberrypi:~/Downloads/ledgerhelpers $ pip3 import ledger
ERROR: unknown command "import"
pi@raspberrypi:~/Downloads/ledgerhelpers $ pip3 install ledger
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ledger
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/ledger/
```

**Comment by Rudd-O** [comment]
That's a bummer -- the Ledger project does not seem to be publishing their Python extension to PyPI.

You can install your distribution's packages for `ledger-python` if you need them.

Give that a shot!  Reopen if that did not work.
