### ISSUE TITLE
Transient failure in unit tests

### ISSUE THREAD

**Issue by porridge** [Rudd-O/ledgerhelpers#28]
I encountered the following failure when running the test suite on v0.3.5 (admittedly with https://github.com/Rudd-O/ledgerhelpers/commit/c421ee39631faf7716b43673cde458870b398f4a but without that the tests fail reliably every time).

I re-ran the tests a few times and this did not occur again, so I suspect it may be a consequence of a race condition somewhere.

```
I: pybuild base:240: cd /home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build; python3.10 -m unittest discover -v 
test_empty_record_auto_goes_last (tests.test_ledgerhelpers.TestGenerateRecord) ... ok
test_no_cleared_date_when_cleared_date_not_supplied (tests.test_ledgerhelpers.TestGenerateRecord) ... ok
test_no_spurious_whitespace (tests.test_ledgerhelpers.TestGenerateRecord) ... ok
test_journal_with_simple_transaction (tests.test_ledgerhelpers.TestJournal) ... /home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:47: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self.setDaemon(True)
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:183: DeprecationWarning: setName() is deprecated, set the name attribute instead
  internal_parsing_thread.setName("Internal reparser")
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:47: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  self.setDaemon(True)
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:344: DeprecationWarning: setName() is deprecated, set the name attribute instead
  self.ledger_parsing_thread.setName("Ledger reparser")
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:107: ResourceWarning: unclosed file <_io.BufferedReader name='/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/tests/testdata/simple_transaction.dat'>
  codecs.open(x, "rb", "utf-8").read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:101: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/tests/testdata/simple_transaction.dat' mode='r' encoding='UTF-8'>
  text = "\n".join(open(x).read() for x in files)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:349: DeprecationWarning: setName() is deprecated, set the name attribute instead
  self.ledger_parsing_thread.setName("Dummy ledger reparser")
ok
test_reload_works (tests.test_ledgerhelpers.TestJournal) ... /home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/tests/test_ledgerhelpers.py:29: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/tests/testdata/simple_transaction.dat' mode='r' encoding='UTF-8'>
  data = open(base.datapath("simple_transaction.dat")).read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:107: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp9ygvjw9g'>
  codecs.open(x, "rb", "utf-8").read()
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:344: DeprecationWarning: setName() is deprecated, set the name attribute instead
  self.ledger_parsing_thread.setName("Ledger reparser")
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:349: DeprecationWarning: setName() is deprecated, set the name attribute instead
  self.ledger_parsing_thread.setName("Dummy ledger reparser")
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:101: ResourceWarning: unclosed file <_io.TextIOWrapper name='/tmp/tmp9ygvjw9g' mode='r' encoding='UTF-8'>
  text = "\n".join(open(x).read() for x in files)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ERROR
test_transactions_with_payee_match (tests.test_ledgerhelpers.TestJournal) ... /home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:344: DeprecationWarning: setName() is deprecated, set the name attribute instead
  self.ledger_parsing_thread.setName("Ledger reparser")
/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/ledgerhelpers/journal.py:101: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/tests/testdata/simple_transaction.dat' mode='r' encoding='UTF-8'>
  text = "\n".join(open(x).read() for x in files)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
ok
test_my_data_file (tests.test_parser.TestParser) ... ok
test_no_end_value (tests.test_parser.TestParser) ... ok
test_simple_transaction (tests.test_parser.TestParser) ... ok
test_with_comments (tests.test_parser.TestParser) ... ok

======================================================================
ERROR: test_reload_works (tests.test_ledgerhelpers.TestJournal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.10_ledgerhelpers/build/tests/test_ledgerhelpers.py", line 34, in test_reload_works
    self.assertEqual(commos["Expenses:Drinking"], "1.00 CHF")
KeyError: 'Expenses:Drinking'

----------------------------------------------------------------------
Ran 10 tests in 0.030s

FAILED (errors=1)
```

**Comment by porridge** [comment]
FWIW, I managed to reproduce it after running the test suite around 200 times in a loop.

**Comment by Rudd-O** [comment]
Sigh.

We may have to add a little bit of an additional timeout if the files are not finished writing by the time the test begins to run.

I'm leaving this open because I don't currently know what needs to change.  However, I've spotted a resource leak which I will fix right now.

**Comment by Rudd-O** [comment]
I've fixed the resource leak.  I can't build ledger python module anymore, so I can't test this.

**Comment by porridge** [comment]
> We may have to add a little bit of an additional timeout if the files are not finished writing by the time the test begins to run.

I don't think this is a problem with filesystem consistency. POSIX guarantees that once the file is `close()`d (and it is) all readers will be able to see the contents immediately. I think the problem here is a race in the `journal.py` code. I'll try to investigate closer, though I have to admit the various threads there made my head spin :-)

**Comment by porridge** [comment]
Here is a somewhat easier to read example:

```
$ PYTHONPATH=src python3 -m unittest tests.test_ledgerhelpers.TestJournal.test_reload_works
1667938179.213593:   DEBUG:      journal.master: Files have changed, rereading.
1667938179.214308:   DEBUG:       journal.slave: Files have changed, rereading.
1667938179.214829:   DEBUG:      journal.master: * Timing:    __run__@Internal reparser                                started
1667938179.215224:   DEBUG:      journal.master: Reparsing internal.
1667938179.215369:   DEBUG:      journal.master: * Timing:    accounts_and_last_commodity_for_account@MainThread       started
1667938179.215402:   DEBUG:       journal.slave: * Timing:    __run__@Ledger reparser                                  started
1667938179.215577:   DEBUG:       journal.slave: Reparsing ledger.
1667938179.215753:   DEBUG:      journal.master: Read 101 characters of journal
1667938179.215731:   DEBUG:  journal.slave.loop: * Servicing: get_accounts_last_commodity_for_account_and_commodities  started
1667938179.216296:   DEBUG:  journal.slave.loop: * Serviced:  get_accounts_last_commodity_for_account_and_commodities  0.001 seconds - new data
1667938179.216369:   DEBUG:       journal.slave: Read 101 characters of journal
1667938179.216780:   DEBUG:       journal.slave: Harvesting accounts and last commodities.
1667938179.217517:   DEBUG:       journal.slave: * Timed:     __run__@Ledger reparser                                  0.002 seconds
1667938179.218429:   DEBUG:      journal.master: * Timed:     __run__@Internal reparser                                0.004 seconds
1667938179.218590:   DEBUG:      journal.master: * Timed:     accounts_and_last_commodity_for_account@MainThread       0.003 seconds
E
======================================================================
ERROR: test_reload_works (tests.test_ledgerhelpers.TestJournal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/tests/test_ledgerhelpers.py", line 38, in test_reload_works
    self.assertEqual(commos["Expenses:Drinking"], "1.00 CHF")
KeyError: 'Expenses:Drinking'

----------------------------------------------------------------------
Ran 1 test in 0.009s

FAILED (errors=1)
```

(The `Read 101 characters of journal` message was inserted right before `_get_text()` returns.)

I'm interpreting this as the slave process receiving and serving a `get_accounts_last_commodity_for_account_and_commodities` request before its initial parsing run has finished. However it is late enough for the initial `changed()` to have run and remembered the timestamps.

For contrast, here is a successful run:

```
1667938195.343500:   DEBUG:      journal.master: Files have changed, rereading.
1667938195.344275:   DEBUG:       journal.slave: Files have changed, rereading.
1667938195.344827:   DEBUG:      journal.master: * Timing:    __run__@Internal reparser                                started
1667938195.345244:   DEBUG:      journal.master: Reparsing internal.
1667938195.345370:   DEBUG:      journal.master: * Timing:    accounts_and_last_commodity_for_account@MainThread       started
1667938195.345452:   DEBUG:       journal.slave: * Timing:    __run__@Ledger reparser                                  started
1667938195.345706:   DEBUG:       journal.slave: Reparsing ledger.
1667938195.346210:   DEBUG:      journal.master: Read 101 characters of journal
1667938195.346245:   DEBUG:       journal.slave: Read 101 characters of journal
1667938195.346721:   DEBUG:       journal.slave: Harvesting accounts and last commodities.
1667938195.348281:   DEBUG:       journal.slave: * Timed:     __run__@Ledger reparser                                  0.003 seconds
1667938195.348495:   DEBUG:  journal.slave.loop: * Servicing: get_accounts_last_commodity_for_account_and_commodities  started
1667938195.348880:   DEBUG:  journal.slave.loop: * Serviced:  get_accounts_last_commodity_for_account_and_commodities  0.000 seconds - new data
1667938195.351072:   DEBUG:      journal.master: * Timed:     __run__@Internal reparser                                0.007 seconds
1667938195.351476:   DEBUG:      journal.master: * Timed:     accounts_and_last_commodity_for_account@MainThread       0.006 seconds
1667938195.351726:   DEBUG:      journal.master: * Timing:    accounts_and_last_commodity_for_account@MainThread       started
1667938195.351946:   DEBUG:  journal.slave.loop: * Servicing: get_accounts_last_commodity_for_account_and_commodities  started
1667938195.352019:   DEBUG:       journal.slave: Files have changed, rereading.
1667938195.352262:   DEBUG:       journal.slave: * Timing:    __run__@Ledger reparser                                  started
1667938195.352453:   DEBUG:       journal.slave: Reparsing ledger.
1667938195.352628:   DEBUG:       journal.slave: Read 202 characters of journal
1667938195.352849:   DEBUG:       journal.slave: Harvesting accounts and last commodities.
1667938195.353785:   DEBUG:       journal.slave: * Timed:     __run__@Ledger reparser                                  0.002 seconds
1667938195.353928:   DEBUG:  journal.slave.loop: * Serviced:  get_accounts_last_commodity_for_account_and_commodities  0.002 seconds - new data
1667938195.354234:   DEBUG:      journal.master: * Timed:     accounts_and_last_commodity_for_account@MainThread       0.003 seconds
.
----------------------------------------------------------------------
Ran 1 test in 0.054s

OK
```

Note that here the `journal.slave: Read 101 characters of journal` message happens before the `get_accounts_last_commodity_for_account_and_commodities` processing.

I *think* a fix might be to either block or return some kind of "try again later" error until the initial parse has finished. 🤔

**Comment by porridge** [comment]
@Rudd-O one possible way to fix this can be seen in [these couple of commits](https://github.com/porridge/ledgerhelpers/compare/various...porridge:ledgerhelpers:fix-race?expand=1). Would be great if you could review/merge #30 so I can avoid rebasing them, or I could push them to that branch as well...

**Comment by Rudd-O** [comment]
You are cleared for takeoff on the issue.  #30 is merged.

**Comment by porridge** [comment]
Thanks, see https://github.com/Rudd-O/ledgerhelpers/pull/31

**Comment by porridge** [comment]
Unfortunately ~the~ a related issue is still there in 3.10, just harder to reproduce. [For one person this happens](http://bugs.debian.org/1108809) in ~44% of cases.
I reproduced this on 11th attempt:

```
python3.13 -m unittest discover -v 
test_empty_record_auto_goes_last (tests.test_ledgerhelpers.TestGenerateRecord.test_empty_record_auto_goes_last) ... ok
test_no_cleared_date_when_cleared_date_not_supplied (tests.test_ledgerhelpers.TestGenerateRecord.test_no_cleared_date_when_cleared_date_not_supplied) ... ok
test_no_spurious_whitespace (tests.test_ledgerhelpers.TestGenerateRecord.test_no_spurious_whitespace) ... ok
test_journal_with_simple_transaction (tests.test_ledgerhelpers.TestJournal.test_journal_with_simple_transaction) ... ok
test_reload_works (tests.test_ledgerhelpers.TestJournal.test_reload_works) ... FAIL
test_transaction_with_zero_posting (tests.test_ledgerhelpers.TestJournal.test_transaction_with_zero_posting) ... ok
test_transactions_with_payee_match (tests.test_ledgerhelpers.TestJournal.test_transactions_with_payee_match) ... ok
test_my_data_file (tests.test_parser.TestParser.test_my_data_file) ... ok
test_no_end_value (tests.test_parser.TestParser.test_no_end_value) ... ok
test_simple_transaction (tests.test_parser.TestParser.test_simple_transaction) ... ok
test_with_comments (tests.test_parser.TestParser.test_with_comments) ... ok

======================================================================
FAIL: test_reload_works (tests.test_ledgerhelpers.TestJournal.test_reload_works)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/porridge/Pulpit/debian/devel/ledgerhelpers/ledgerhelpers/.pybuild/cpython3_3.13_ledgerhelpers/build/tests/test_ledgerhelpers.py", line 40, in test_reload_works
    self.assertEqual(commos["Expenses:Drinking"], "1.00 EUR")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 1.00 CHF != '1.00 EUR'

----------------------------------------------------------------------
Ran 11 tests in 0.020s

FAILED (failures=1)
```

Edit: it's actually a different failure. The original issue was that on initial read the key wasn't there. Now the value _after rewriting the file_ is stale.

**Comment by porridge** [comment]
I ran some experiments, and it turns out (to my surprise) that `st_mtime` is **not updated** if the file contents change within some (millisecond-scale) time window after `st_mtime` was last updated:

```python
#!/usr/bin/python3
import os
import tempfile
import time


def ping(f):
    print("before write, at %-20s, file mtime is %-20s" % (time.time(), os.stat(f.name).st_mtime))
    f.write('x')
    f.flush()
    print("after  write, at %-20s, file mtime is %-20s" % (time.time(), os.stat(f.name).st_mtime))


delay = 0.001


with tempfile.NamedTemporaryFile(mode="w") as f:  # same results with with open("/tmp/xx", mode="w")
    for n in range(20):
        ping(f)
        time.sleep(delay)
```

I'm seeing for example:

```
$ ./repro.py 
before write, at 1751726696.0424693  , file mtime is 1751726696.0406768  
after  write, at 1751726696.0424914  , file mtime is 1751726696.0406768  
before write, at 1751726696.0435593  , file mtime is 1751726696.0406768  
after  write, at 1751726696.0435746  , file mtime is 1751726696.0406768  
before write, at 1751726696.0446389  , file mtime is 1751726696.0406768  
after  write, at 1751726696.0446498  , file mtime is 1751726696.0406768  
before write, at 1751726696.0457172  , file mtime is 1751726696.0406768  
after  write, at 1751726696.045748   , file mtime is 1751726696.0446768  
before write, at 1751726696.0469224  , file mtime is 1751726696.0446768  
after  write, at 1751726696.0469942  , file mtime is 1751726696.0446768  
before write, at 1751726696.0481014  , file mtime is 1751726696.0446768  
after  write, at 1751726696.0481405  , file mtime is 1751726696.0446768  
before write, at 1751726696.0492203  , file mtime is 1751726696.0446768  
after  write, at 1751726696.049259   , file mtime is 1751726696.0486767  
before write, at 1751726696.050331   , file mtime is 1751726696.0486767  
after  write, at 1751726696.0503435  , file mtime is 1751726696.0486767  
before write, at 1751726696.051409   , file mtime is 1751726696.0486767  
after  write, at 1751726696.0514205  , file mtime is 1751726696.0486767  
before write, at 1751726696.052486   , file mtime is 1751726696.0486767  
after  write, at 1751726696.0524983  , file mtime is 1751726696.0486767  
before write, at 1751726696.053566   , file mtime is 1751726696.0486767  
after  write, at 1751726696.0535796  , file mtime is 1751726696.0526767  
before write, at 1751726696.0546474  , file mtime is 1751726696.0526767  
after  write, at 1751726696.0546594  , file mtime is 1751726696.0526767  
before write, at 1751726696.0557246  , file mtime is 1751726696.0526767  
after  write, at 1751726696.0557373  , file mtime is 1751726696.0526767  
before write, at 1751726696.056805   , file mtime is 1751726696.0526767  
after  write, at 1751726696.0568163  , file mtime is 1751726696.0526767  
before write, at 1751726696.0578825  , file mtime is 1751726696.0526767  
after  write, at 1751726696.0578978  , file mtime is 1751726696.0566769  
before write, at 1751726696.0589662  , file mtime is 1751726696.0566769  
after  write, at 1751726696.05898    , file mtime is 1751726696.0566769  
before write, at 1751726696.0600479  , file mtime is 1751726696.0566769  
after  write, at 1751726696.0600607  , file mtime is 1751726696.0566769  
before write, at 1751726696.0611281  , file mtime is 1751726696.0566769  
after  write, at 1751726696.061141   , file mtime is 1751726696.0606768  
before write, at 1751726696.0622096  , file mtime is 1751726696.0606768  
after  write, at 1751726696.0622234  , file mtime is 1751726696.0606768  
before write, at 1751726696.0632906  , file mtime is 1751726696.0606768  
after  write, at 1751726696.0633013  , file mtime is 1751726696.0606768  
$ LANG=C stat /tmp/xx
  File: /tmp/xx
  Size: 20        	Blocks: 8          IO Block: 4096   regular file
Device: 0,42	Inode: 28995       Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/porridge)   Gid: ( 1000/porridge)
Access: 2025-07-05 16:40:58.484271732 +0200
Modify: 2025-07-05 16:44:56.060676795 +0200
Change: 2025-07-05 16:44:56.060676795 +0200
 Birth: 2025-07-05 16:40:58.484271732 +0200
```

Note the last three writes are never reflected in the timestamp...

Same result on tmpfs and ext4...

**Comment by porridge** [comment]
Ah, [this comment](https://unix.stackexchange.com/questions/11599/determine-file-system-timestamp-precision#comment762968_11599) sheds some light on the cause of this behaviour..

**Comment by Rudd-O** [comment]
Thanks for your PRs!
