### ISSUE TITLE
parse include properly

### ISSUE THREAD

**Issue by 8h2a** [Rudd-O/ledgerhelpers#4]
The moment i started "buy" i got this error message:

> Cannot open ledger file: unparsable data at line 1, char 1

And the following stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/buy", line 5, in <module>
    pkg_resources.run_script('ledgerhelpers==0.0.20', 'buy')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/EGG-INFO/scripts/buy", line 11, in <module>
    sys.exit(buy.main())
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/programs/buy.py", line 276, in main
    journal, s = common.load_journal_and_settings_for_gui()
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/__init__.py", line 44, in f
    return kallable(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/__init__.py", line 955, in load_journal_and_settings_for_gui
    cannot_start_dialog("Cannot open ledger file: %s" % e)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/__init__.py", line 927, in <lambda>
    cannot_start_dialog = lambda msg: FatalError("Cannot start program", msg, outside_mainloop=True)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/__init__.py", line 924, in FatalError
    d.run()
KeyboardInterrupt
```

My setup: The first and only line in my main ledger file is an "include ..." which includes another ledger file.
The included ledger file also has an "include" to include the previous ledger file (from the previous year). This won't work if the include path is relative:

> While parsing file "", line 1:
> Error: File to include was not found: [...]

Once i fixed that i noticed that i had to remove the next line which was "D 1,000.00 €". So i removed that line as well. Then i got the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/buy", line 5, in <module>
    pkg_resources.run_script('ledgerhelpers==0.0.20', 'buy')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/EGG-INFO/scripts/buy", line 11, in <module>
    sys.exit(buy.main())
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/programs/buy.py", line 282, in main
    win = klass(journal, s, " ".join(args) if args else None)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/programs/buy.py", line 101, in __init__
    BuyWindow.__init__(self)
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/programs/buy.py", line 37, in __init__
    self.amount = common.LedgerAmountEntry()
  File "/usr/local/lib/python2.7/dist-packages/ledgerhelpers-0.0.20-py2.7.egg/ledgerhelpers/__init__.py", line 738, in __init__
    self.display.set_xalign(1.0)
AttributeError: 'Label' object has no attribute 'set_xalign'
```

**Comment by Rudd-O** [comment]
I need to address the include problem as it's a legit bug, and so is the D as well.

The other issue you refer to is a matter of figuring out what GTK+ version you have on your system, because I fear you might have a strange version -- `set_xalign()` is a documented method of GtkLabel so that shouldn't give you any sort of problem.

**Comment by Rudd-O** [comment]
Reminder for myself to notify the author of this pull request when the include issue is fixed:

https://github.com/Rudd-O/ledgerhelpers/pull/1

**Comment by 8h2a** [comment]
I'm using Ubuntu 14.04
python-gtk2                                 2.24.0-3ubuntu3

**Comment by Rudd-O** [comment]
Do you have python gobject 3?  Python-GTK2 is not enough.  I don't know how your error happened given that the script demands version 3.:

#!/usr/bin/env python

```
import datetime
from gi.repository import GObject
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
import sys
import threading
```

It's obviously demanding Gtk 3 before instantiating the wrappers.  Gtk 2 doesn't have that method, but Gtk 3 does.  This is maddening.  How would we go about finding out which version of Gtk is being imported here, on your machine?

**Comment by 8h2a** [comment]
Yes, I do have python-gobject 3.12.0-1ubuntu1

**Comment by Rudd-O** [comment]
So can you check this out?

```
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
help (Gtk.Label.set_xalign)
```

and see if you get that AttributeError again?

**Comment by 8h2a** [comment]
I get the same error message again:

> AttributeError: type object 'Label' has no attribute 'set_xalign'

Apparently my python uses the version "libgtk-3-0:amd64 3.10.8-0ubuntu1.6".
I checked it with:

```
>>> Gtk.get_major_version()
3L
>>> Gtk.get_minor_version()
10L
>>> Gtk.get_micro_version()
8L
```

**Comment by Rudd-O** [comment]
Something is bugged with your Gtk+.  Can you file a bug report with
Ubuntu about labels not having set_xalign()?  That is a normal method in
Gtk+ 3 and higher.

## 

```
Rudd-O
http://rudd-o.com/
```

**Comment by 8h2a** [comment]
Apparently this function is only available in version 3.16 and above.

**Comment by Rudd-O** [comment]
On 02/14/2016 01:04 PM, d wrote:

> Apparently this function is only available in version 3.16 and above.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Rudd-O/ledgerhelpers/issues/4#issuecomment-183884527.

How did you find out about that?

## 

```
Rudd-O
http://rudd-o.com/
```

**Comment by 8h2a** [comment]
https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-xalign

> Since: 3.16

**Comment by Rudd-O** [comment]
OK.  I have pushed a fix that stops using `set_xalign()`.  It should be tagged 0.0.21 and I'd like your feedback.

**Comment by Rudd-O** [comment]
As for how `include` should be dealt with, the parsing of the file needs to be done in such a way that there need to be two parsing modes:

Mode A treats includes by simply tokenizing them as stanzas, but does not attempt to include anything.  The resulting data structure contains include tokens.

Mode B recursively parses includes.  The resulting data structure contains the tokens from the included files in lieu of the includes.

Mode A is necessary for things like sorting the data file.  Mode B is necessary for things like producing autocomplete transactions in `addtrans`.

**Comment by 8h2a** [comment]
Thanks! It seems to be working now.

The issue with the "D 1,000.00 €" still remains though.
And i found a new minor bug: In the UI it says "$" everywhere, but when it saves the transaction it's actually "€". (The stored transaction is correct). 

And it uses "," instead of "." for the currency.
e.g. "€ -13,00" instead of "€ -13.00".
That is because of the aforementioned missing default commodity setting.

Should i open up new issues to discuss them separately?

**Comment by Rudd-O** [comment]
Yes please, thank you!

**Comment by hoclun-rigsep** [comment]
Bumping this issue; I would like to use addtrans but the structure of my includes takes precedence.

**Comment by phylor** [comment]
@Rudd-O Are you still planning to add support for the `include` directive? I'd love to use `addtrans`, but can't because it doesn't like the `include` directive.

**Comment by Rudd-O** [comment]
I am planning to, because I need to get `addtrans` to work with Beancount as well, and -- quite frankly -- both Ledger and Beancount require support for `include`.
